[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]

[dependencies]
# build-dependencies
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
compilers = ">=1.11.0,<2"
doxygen = ">=1.13.2,<2"
lcov = ">=1.16,<2"
scikit-build-core = ">=0.11.6,<0.12"


# Python things
python = ">=3.14.0,<3.15"
nanobind = ">=2.9.2,<3"
pip = ">=25.2,<26"

# dev dependencies
cppcheck = ">=2.18.3,<3"
include-what-you-use = ">=0.25,<0.26"
ipython = ">=9.6.0,<10"
pytest = ">=8.4.2,<9"
mypy = ">=1.18.2,<2"
# C++ testing
catch2 = ">=3.8.0,<4"

[pypi-dependencies]
ruff = ">=0.14.3, <0.15"
zuban = ">=0.2.1, <0.3"
