[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
# build-dependencies
cmake = "*"
ninja = ">=1.13.1,<2"
compilers = ">=1.11.0,<2"
doxygen = ">=1.13.2,<2"
lcov = ">=1.16,<2"
scikit-build-core = ">=0.11.6,<0.12"

# Python things
python = ">=3.10"
nanobind = ">=2.9.2,<3"
pip = "*"
uv = "*"

# dev dependencies
cppcheck = "*"
include-what-you-use = "*"
ipython = "*"
pytest = "*"
mypy = "*"

# C++ testing
catch2 = ">=3.8.0,<4"

[pypi-dependencies]
ruff = "*"
zuban = "*"
